
package com.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://service.ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "test", targetNamespace = "http://service.ws.com/", className = "com.ws.service.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://service.ws.com/", className = "com.ws.service.TestResponse")
    @Action(input = "http://service.ws.com/HelloService/testRequest", output = "http://service.ws.com/HelloService/testResponse")
    public void test();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "shello", targetNamespace = "http://service.ws.com/", className = "com.ws.service.Shello")
    @ResponseWrapper(localName = "shelloResponse", targetNamespace = "http://service.ws.com/", className = "com.ws.service.ShelloResponse")
    @Action(input = "http://service.ws.com/HelloService/shelloRequest", output = "http://service.ws.com/HelloService/shelloResponse")
    public String shello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
